(define deck '())
(define (set-deck!) (set! deck (make-deck)))

(define (game)
	(set-deck!)
	(define computer-pile '())
	(define user-pile '())
	(define computer-score 0)
	(define user-score 0)
	(let ((piles (init-piles (lambda (x) (append x (pop))) (lambda (x) (append x (pop)))
		)))
		(set! computer-pile (car piles))
		(set! user-pile (cdr piles))
	)
	(draw user-pile)
	(let ((who (who-starts?)))
		(ndisplay who "starts first")
	)
	(print-winner computer-score user-score)
(game))