(define deck '())
(define (set-deck!) (set! deck (make-deck)))
(define user-asked-pile '())
(define (set-user-asked-pile!) 
 (set! user-asked-pile (make-empty-avl-tree string<? string=?)))

(define (game)
 (set-deck!)
 (set-user-asked-pile!)
 (define computer-score 0)
 (define user-score 0)
 (let ((piles (init-piles (lambda (x) (append x (pop))) (lambda (x) (append x (pop)))
  )))
  (set! computer-pile (car piles))
  (set! user-pile (cdr piles))
 )
 (draw user-pile)
 (let ((who (who-starts?)))
  (ndisplay who "starts first")
 )
 (print-winner computer-score user-score)
(game))